apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicd-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
        - name: webserver
          image: kimjuhyo/k8s
          ports:
            - containerPort: 8080
